config:
  source:
    connectionString:
    database:
  destiny:
    connectionString:
    database:
  tenants:
    -
collections:
  - name:
    batchSize: "all"
    upsert:
    multiTenant:
    filter: |
      {
      
      }