on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  build:
    strategy:
      matrix:
        go-version: [1.22, 1.23]
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Restore Go test cache
        id: cache-go-test
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.go-version }}

      - name: Generate Binary file
        run: |
          GOOS=$(echo ${{ matrix.os }} | sed 's/ubuntu/linux/' | sed 's/windows/windows/' | sed 's/macos/darwin/') \
          GOARCH=${{ matrix.arch }} \
          go build -o app-${{ matrix.os }}-${{ matrix.arch }} ./...

      - name: Runing tests
        run: go test ./...
        
      - name: Save Go test cache
        if: always()
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}-${{ matrix.go-version }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.go-version }}