on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  build:
    strategy:
      matrix:
        go-version: [1.22, 1.23]
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Restore Go test cache
        id: cache-go-test
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.go-version }}

      - name: Determine GOOS and GOARCH
        id: set-env
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "GOOS=linux" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "GOOS=windows" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "GOOS=darwin" >> $GITHUB_ENV
          fi

          if [[ "${{ matrix.arch }}" == "amd64" ]]; then
            echo "GOARCH=amd64" >> $GITHUB_ENV
          elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
            echo "GOARCH=arm64" >> $GITHUB_ENV
          fi

      - name: Skip unsupported combinations
        if: ${{ (env.GOOS == 'windows' && env.GOARCH == 'arm64') || (env.GOOS == 'darwin' && env.GOARCH == 'arm64') }}
        run: |
          echo "Skipping unsupported GOOS/GOARCH pair: $GOOS/$GOARCH"
          exit 0

      - name: Generate Binary file
        run: go build -o app-${{ env.GOOS }}-${{ env.GOARCH }} ./...

      - name: Runing tests
        run: go test ./...
        
      - name: Save Go test cache
        if: always()
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}-${{ matrix.go-version }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.go-version }}