name: Build and Release Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22, 1.23]
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Build
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest)
              GOOS=linux
              ;;
            macos-latest)
              GOOS=darwin
              ;;
            windows-latest)
              GOOS=windows
              ;;
          esac
          GOARCH=${{ matrix.arch }}
          go build -o mongo-mirror-${{ matrix.os }}-${{ matrix.arch }} ./cmd/...

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release notes for version ${{ github.ref_name }}."

      - name: Upload Release Assets
        if: ${{ steps.create_release.outputs.upload_url }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mongo-mirror-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: mongo-mirror-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream