name: Build and Release Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23]
        os: [windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Go binaries
        run: |
          mkdir -p output
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o mongo-mirror-${{ matrix.os }}-${{ matrix.arch }}
        
          
          - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          tag_name: ${{ needs.changelog.outputs.tag }}
          prerelease: false
          draft: false
          files: mongo-mirror-*
          generate_release_notes: true
          name: ${{ needs.changelog.outputs.tag }}
          body: |
            <details>
              <summary>🤖 Autogenerated Conventional Changelog</summary>

            ${{ needs.changelog.outputs.clean_changelog }}
            </details>